# Secrets for AuthorWorks K3d Deployment
# This file uses envsubst for variable substitution
# Set environment variables or use .env file before deploying

apiVersion: v1
kind: Secret
metadata:
  name: authorworks-secrets
  namespace: authorworks
type: Opaque
stringData:
  # Database - uses external PostgreSQL
  # POSTGRES_HOST: homelab=neon-postgres-leopaska, local=localist-postgres-local
  DATABASE_URL: "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-host.docker.internal}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-authorworks}"
  LOGTO_DATABASE_URL: "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-host.docker.internal}:${POSTGRES_PORT:-5432}/logto"
  
  # Redis - uses external Redis
  # REDIS_HOST: homelab=redis-nd-leopaska, local=localist-redis-local
  REDIS_URL: "redis://:${REDIS_PASSWORD}@${REDIS_HOST:-host.docker.internal}:${REDIS_PORT:-6379}"
  
  # MinIO/S3 - uses external MinIO
  # MINIO_HOST: homelab=minio-leopaska, local=localist-minio-local
  S3_ENDPOINT: "http://${MINIO_HOST:-host.docker.internal}:${MINIO_PORT:-9000}"
  S3_ACCESS_KEY: "${MINIO_ROOT_USER:-minioadmin}"
  S3_SECRET_KEY: "${MINIO_ROOT_PASSWORD:-minioadmin}"
  S3_BUCKET: "authorworks"
  
  # Authentication (Logto - deployed in cluster)
  JWT_SECRET: "${JWT_SECRET:-change-this-secret}"
  LOGTO_ENDPOINT: "http://logto:3001"
  LOGTO_CLIENT_ID: "${LOGTO_CLIENT_ID:-authorworks-app}"
  LOGTO_CLIENT_SECRET: "${LOGTO_CLIENT_SECRET:-change-from-console}"
  
  # Stripe (optional - for subscription service)
  STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY:-}"
  STRIPE_WEBHOOK_SECRET: "${STRIPE_WEBHOOK_SECRET:-}"
  STRIPE_PRICE_PRO: "${STRIPE_PRICE_PRO:-}"
  STRIPE_PRICE_ENTERPRISE: "${STRIPE_PRICE_ENTERPRISE:-}"
  
  # AI Services (for content worker)
  ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY:-}"
  OPENAI_API_KEY: "${OPENAI_API_KEY:-}"
  ELEVENLABS_API_KEY: "${ELEVENLABS_API_KEY:-}"
  
  # RabbitMQ (deployed in cluster)
  RABBITMQ_URL: "amqp://authorworks:authorworks123@rabbitmq:5672"
  
  # Elasticsearch (deployed in cluster)
  ELASTICSEARCH_URL: "http://elasticsearch:9200"

