apiVersion: v1
kind: Secret
metadata:
  name: authorworks-secrets
  namespace: authorworks
type: Opaque
stringData:
  database-url: "postgresql://postgres:password@postgres.database:5432/authorworks"
  redis-url: "redis://:password@redis.cache:6379"
  minio-access-key: "minioadmin"
  minio-secret-key: "minioadmin"
---
apiVersion: v1
kind: Secret
metadata:
  name: tenant-1-secrets
  namespace: authorworks-tenant-1
type: Opaque
stringData:
  database-url: "postgresql://tenant1:password@postgres.database:5432/tenant1_db"
  redis-url: "redis://:password@redis.cache:6379/1"
---
apiVersion: v1
kind: Secret
metadata:
  name: tenant-2-secrets
  namespace: authorworks-tenant-2
type: Opaque
stringData:
  database-url: "postgresql://tenant2:password@postgres.database:5432/tenant2_db"
  redis-url: "redis://:password@redis.cache:6379/2"