---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-registry-credentials
  namespace: authorworks
spec:
  encryptedData:
    .dockerconfigjson: AgCpkd6R0OKW4hxKV8qhVKRA2L+LuXgF2k94NpklhQHBtYZmhXcJWb2PD/36TONbJVaW6l0ON+9aHqHQ9RxSvQYWbDwPhLCnPxJLQ4QUQFdSf7SI4vMYtyVGId27EXYurL4dToP+h4PgnG6+MJQQ6XZXwGYTWonzfDqkxwUtDkGBF4r4Gs6SqLNTdxSWpC1zGGf0EwrAcmQ30sVyziBIOs5HpjCauWhCTeEVcZojZ2BfbmyrbLMl8YBuPoxtR/N4vStVkFd4NAcZNx6/qOPl5Pj7mpMmTGRFM9qrbGF6P1X9zZ6w1oGlLG/cGqNYOD0mFIwh9WejMScCEq+NrwU9JLGxg86Y7WaSUKNIrEBVSahuvX4tKeXCRFaawt+RRatAJlbdosjkAwflFtMJqiO6Yh6K5ncXNIUJfxPwMujIazpPswHefQbtuilZuvzT5Xlnta5TvgQ7rLhEGgyszmeugYz3j+rc60RYfz7DbDYv9LG//wvUOqz0RCIkeRsUyzlFnb9HVE3Lam5PX0cUrbTKBHiNfwsbMO1NlXJI5x6G3DFgijHp0gLdShbnVcPVhTne6UosfOHkxJqrldN2XBmf6ucOPYTwHKlEYz5Tb1A7Z/va05x4tU2zwqAvDXntJCRS9QQgllFZorHDYytww1fhOX7ae2MEktITDhQF1Ni8cauyGvh47WJolZXqKs6Er/8xMsndgrqtE0Yg+pueihE3UAkkxe7RI+z+UZwhatiQBNOPt1CzK+E3oH/WiO6uWAdLBKd/WYIdfUy3VT+IQpeO/s+Sj6gqSwHEMZdFUoJue6i7Yx+4ZtofBTOSAkw7sd8b3mxtbWE4sm8HmqCeJ8ha7hONOtJeyuuHNzpLMS/iOOE7pXm570Y9QUBH9kQ0dxH0d4OUPYk0BcUr+PXKplGBWvB8jCpF/Rbl8F7iC3glCw==
  template:
    metadata:
      name: forgejo-registry-credentials
      namespace: authorworks
    type: kubernetes.io/dockerconfigjson
