---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: authorworks
spec:
  encryptedData:
    .dockerconfigjson: AgBTRy6sC4M4EHCxWl4VF4e95aHjWgZCEVuObAD3o9ikshq104g63/CHLUja81nX/ib+4uXqDQSnhzV422151aB51nZHoWXpnAk8iaJrCTJ+zwugvX853OkPxjBn4AsIs1QJc0mFhS8SFWM3oBWwDzcr0NIWNBOoQWRcKOOnMSTkURI3wEmQgZ1kLikru/di9CCFl6o8o1H7NPJ0IEueAm0inrKL1EgGWs+ER9PHuUicF3wzYtG8VYJcBUtjmbgKZTCwMMUK+2csR0chPkRP3Cl55Ins8JaOKIBpvTzc9TOBuwdk3NFMZGz7+PRQRxpoLFxeMNViyGqh5KSMlWBPzEzTWncx7J7ZR6SwbyCq3OERoyi87NjuqcE+4+Cxe+m5XkMiv2aPIqdP0D27PKl7UxHm6qaSA9R1ScE8VL7H8qe84sB2hF8WuhR9inDBlfF82xTj5nfMNPgpsTY8FlRmit6EMBG++goUexHmuFUv5THdR926MY9PQ6wmw6/a4GJuhX1dsxxNtEE6JB39EvuIWl9B4S6STzHkB3AQEa2xWLPCt7ya7J4f0IElmJkQWua08IguJ0l8IcrlAGCspxejekwqKIJX9bpO10zBIcgDneqBZekV0pTapaOos7A1YBxn/smvht1iTcSGwfjJ6cHAVOPQVqpdnNyslALLhatsguqXbErNoceqssYNI8i3RTj9aSANXICM0wTV/PQMPlFoLi5RjXk6E+njN1F9IfFGDpv1coyR2dcjzsPhX3mqyhNTxdDVLJBse3mZwTl4m0HP2+9dSTHcSpVwc3M9M+53azAkbd7D+QRtxN6wMin3qvG3u6QmTjrQtgXzhUJb+886JQUTyMTYaZ8ZkiaIxM15G3RrjLlK8LY9mdSPUFn3tAgAHb7PsMT1ot1mKjWZHUIjsOF61EmQbvQ4sf4caUskj9F+eGw=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: authorworks
    type: kubernetes.io/dockerconfigjson
